const rspTheme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "react-spectrum-RichTextEditor-placeholder",
  paragraph: "react-spectrum-RichTextEditor-paragraph",
  quote: "react-spectrum-RichTextEditor-quote",
  heading: {
    h1: "react-spectrum-RichTextEditor-heading-h1",
    h2: "react-spectrum-RichTextEditor-heading-h2",
    h3: "react-spectrum-RichTextEditor-heading-h3",
    h4: "react-spectrum-RichTextEditor-heading-h4",
    h5: "react-spectrum-RichTextEditor-heading-h5",
  },
  list: {
    nested: {
      listitem: "react-spectrum-RichTextEditor-nested-listitem",
    },
    ol: "react-spectrum-RichTextEditor-list-ol",
    ul: "react-spectrum-RichTextEditor-list-ul",
    listitem: "react-spectrum-RichTextEditor-listitem",
  },
  image: "react-spectrum-RichTextEditor-image",
  link: "react-spectrum-RichTextEditor-link",
  text: {
    bold: "react-spectrum-RichTextEditor-text-bold",
    italic: "react-spectrum-RichTextEditor-text-italic",
    overflowed: "react-spectrum-RichTextEditor-text-overflowed",
    hashtag: "react-spectrum-RichTextEditor-text-hashtag",
    underline: "react-spectrum-RichTextEditor-text-underline",
    strikethrough: "react-spectrum-RichTextEditor-text-strikethrough",
    underlineStrikethrough:
      "react-spectrum-RichTextEditor-text-underlineStrikethrough",
    code: "react-spectrum-RichTextEditor-text-code",
  },
  code: "react-spectrum-RichTextEditor-code",
  codeHighlight: {
    atrule: "react-spectrum-RichTextEditor-tokenAttr",
    attr: "react-spectrum-RichTextEditor-tokenAttr",
    boolean: "react-spectrum-RichTextEditor-tokenProperty",
    builtin: "react-spectrum-RichTextEditor-tokenSelector",
    cdata: "react-spectrum-RichTextEditor-tokenComment",
    char: "react-spectrum-RichTextEditor-tokenSelector",
    class: "react-spectrum-RichTextEditor-tokenFunction",
    "class-name": "react-spectrum-RichTextEditor-tokenFunction",
    comment: "react-spectrum-RichTextEditor-tokenComment",
    constant: "react-spectrum-RichTextEditor-tokenProperty",
    deleted: "react-spectrum-RichTextEditor-tokenProperty",
    doctype: "react-spectrum-RichTextEditor-tokenComment",
    entity: "react-spectrum-RichTextEditor-tokenOperator",
    function: "react-spectrum-RichTextEditor-tokenFunction",
    important: "react-spectrum-RichTextEditor-tokenVariable",
    inserted: "react-spectrum-RichTextEditor-tokenSelector",
    keyword: "react-spectrum-RichTextEditor-tokenAttr",
    namespace: "react-spectrum-RichTextEditor-tokenVariable",
    number: "react-spectrum-RichTextEditor-tokenProperty",
    operator: "react-spectrum-RichTextEditor-tokenOperator",
    prolog: "react-spectrum-RichTextEditor-tokenComment",
    property: "react-spectrum-RichTextEditor-tokenProperty",
    punctuation: "react-spectrum-RichTextEditor-tokenPunctuation",
    regex: "react-spectrum-RichTextEditor-tokenVariable",
    selector: "react-spectrum-RichTextEditor-tokenSelector",
    string: "react-spectrum-RichTextEditor-tokenSelector",
    symbol: "react-spectrum-RichTextEditor-tokenProperty",
    tag: "react-spectrum-RichTextEditor-tokenProperty",
    url: "react-spectrum-RichTextEditor-tokenOperator",
    variable: "react-spectrum-RichTextEditor-tokenVariable",
  },
};

export default rspTheme;
